spring.application.name=SalaryDemoProject

server.port=2006

#connection properties

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/soataskdb
spring.datasource.username=root
spring.datasource.password=Manjusha7@

#hibernate properties

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect (dialect represents which format we are using)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#this property is used for neat alignment
spring.jpa.properties.hibernate.format_sql=true
